CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  senha VARCHAR(100) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tasks (
  id SERIAL PRIMARY KEY,
  titulo VARCHAR(100) NOT NULL,
  descricao TEXT,
  status VARCHAR(50) NOT NULL,
  tempo VARCHAR(20),
  tag VARCHAR(50),
  categoria VARCHAR(50),
  prazo TIMESTAMP,
  user_id INTEGER REFERENCES users(id),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
